Allow to decrease pre-staking values.
ice-blockchain/freezer pull request #106
Opened 2024-01-23 16:45 UTC by ice-myles

Allow to decrease pre-staking values.

2024-01-23 17:19 UTC, ice-ares requested changes
What about miner? Or other parts of the service? Is this everything needed? I remember when we did the prestaking reset for everyone we changed a bit more files

2024-01-23 17:19 UTC, ice-ares commented on cmd/freezer-refrigerant/contract.go
> -		Years      uint8  `json:"years" required:"true" maximum:"5" example:"1"`
No, rollback. But make em *uint8

2024-01-23 17:19 UTC, ice-ares commented on cmd/freezer-refrigerant/tokenomics.go
> +			Years:      &years,
U dont need pointers here

2024-01-23 17:19 UTC, ice-ares commented on tokenomics/pre_staking.go
> +	preStakingResettable struct {
Why dont u use the other struct and modify its fields to be resettable?

2024-01-23 17:19 UTC, ice-ares commented on tokenomics/pre_staking.go
> -		if (existing.PreStakingAllocation == 100 || existing.PreStakingAllocation == st.Allocation) &&
Keep the other conditions as well

2024-01-23 19:26 UTC, ice-myles commented on tokenomics/pre_staking.go
> +	preStakingResettable struct {
To make possibility to reset values to 0, so these fields are resettable.

2024-01-23 19:27 UTC, ice-myles commented on tokenomics/pre_staking.go
> -		if (existing.PreStakingAllocation == 100 || existing.PreStakingAllocation == st.Allocation) &&
Why? If user has set maximum value, will not he able to reset this to < max or to 0?

2024-01-23 19:29 UTC, ice-ares commented on tokenomics/pre_staking.go
> +	preStakingResettable struct {
Yea, use the other structure, 3 lines above

2024-01-23 19:29 UTC, ice-ares commented on tokenomics/pre_staking.go
> -		if (existing.PreStakingAllocation == 100 || existing.PreStakingAllocation == st.Allocation) &&
Cuz it still needs to be between a min and a max

2024-01-23 19:30 UTC, ice-myles commented on cmd/freezer-refrigerant/tokenomics.go
> +			Years:      &years,
If years and allocation will not be pointers, then they will not be returned to FE in case if they are 0 values. Don't we need to return them like
```
{
  "userId": "4e8e862f-78ee-4c17-9a82-f3a5769ccc25",
  "years": 0,
  "allocation": 0,
  "bonus": 0
}
```

Will this response affect on FE in bad way? FE admits all values, as it has slider, isn't it?
```
{
  "userId": "4e8e862f-78ee-4c17-9a82-f3a5769ccc25"
}
```

2024-01-23 19:32 UTC, ice-myles commented
> What about miner? Or other parts of the service? Is this everything needed? I remember when we did the prestaking reset for everyone we changed a bit more files

We have just reset Bonus and Allocation values to 0 for all users. We did it inside the miner. And now user can set these values by response. All other work mining.go does, as it recalculates BalanceTotalPreStaking depending on new values.

2024-01-23 19:35 UTC, ice-myles commented on tokenomics/pre_staking.go
> +	preStakingResettable struct {
> use the other structure, 3 lines above

Why other structure? `preStakingResettable` should be used to store values from 0 to max.

2024-01-23 19:41 UTC, ice-myles commented on tokenomics/pre_staking.go
> -		if (existing.PreStakingAllocation == 100 || existing.PreStakingAllocation == st.Allocation) &&
But here was check not to change values if the existing is max/the same as in the response.
If I keep those conditions, then user that has Allocation == 100 and Years == MAX, will not be able to change his pre staking values to lower values.

2024-01-23 19:43 UTC, ice-myles commented on tokenomics/pre_staking.go
> +	preStakingResettable struct {
A, you mean to do the first structure with resettable fields probably?
I did the second with resettable as we had 1 bug recently related to read/write, so decided to split read and write structures just to be sure that the data will not be affected at the wrong places in the future.
Then still use the first?

2024-01-24 00:45 UTC, ice-ares commented on cmd/freezer-refrigerant/tokenomics.go
> +			Years:      &years,
Just remove omitempty

2024-01-24 00:46 UTC, ice-ares commented on tokenomics/pre_staking.go
> +	preStakingResettable struct {
Yea, reuse it

2024-01-24 00:48 UTC, ice-ares commented on tokenomics/pre_staking.go
> -		if (existing.PreStakingAllocation == 100 || existing.PreStakingAllocation == st.Allocation) &&
Well, then add validation in cmd for the values to be between 0-5 and 0-100

2024-01-24 00:49 UTC, ice-ares commented
> > What about miner? Or other parts of the service? Is this everything needed? I remember when we did the prestaking reset for everyone we changed a bit more files
> 
> 
> 
> We have just reset Bonus and Allocation values to 0 for all users. We did it inside the miner. And now user can set these values by response. All other work mining.go does, as it recalculates BalanceTotalPreStaking depending on new values.

So this is everything we need to change for prestaking to be able to be reset properly for users?

2024-01-24 06:02 UTC, ice-myles commented on tokenomics/pre_staking.go
> -		if (existing.PreStakingAllocation == 100 || existing.PreStakingAllocation == st.Allocation) &&
```
if *req.Data.Years > tokenomics.MaxPreStakingYears {
		*req.Data.Years = tokenomics.MaxPreStakingYears
	}
	if *req.Data.Allocation > maxAllocation {
		*req.Data.Allocation = maxAllocation
	}
```
Checks max values.

If to set -1 for any of both fields -> `STRUCTURE_VALIDATION_FAILED`
If not to specify any of them in the request -> `MISSING_PROPERTIES`

So everything is handled already.

2024-01-24 06:03 UTC, ice-myles commented
> > > What about miner? Or other parts of the service? Is this everything needed? I remember when we did the prestaking reset for everyone we changed a bit more files
> > 
> > 
> > We have just reset Bonus and Allocation values to 0 for all users. We did it inside the miner. And now user can set these values by response. All other work mining.go does, as it recalculates BalanceTotalPreStaking depending on new values.
> 
> So this is everything we need to change for prestaking to be able to be reset properly for users?

Yes. Here is that PR https://github.com/ice-blockchain/freezer/pull/49. It just sets Allocation and Bonus to 0 for every user in the miner.

2024-01-24 08:03 UTC, merged