reset / disable prestakings in case of quiz reset
ice-blockchain/freezer pull request #108
Opened 2024-01-26 11:27 UTC by ice-cronus

2024-01-26 14:30 UTC, ice-myles commented on miner/mining.go
> +		updatedUser.PreStakingAllocationResettableField = model.PreStakingAllocationResettableField{&zero}
Here is PreStakingAllocationResettableField and PreStakingAllocationField has the same redis field name. Don't they crossing if you set both together on
```
            for _, value := range updatedUsers {
				if err := pipeliner.HSet(reqCtx, value.Key(), storage.SerializeValue(value)...).Err(); err != nil {
					return err
				}
			}
```
cal in miner? Or FlexibleFloat64 allow to do this?

2024-01-26 14:33 UTC, ice-cronus commented on miner/mining.go
> +		updatedUser.PreStakingAllocationResettableField = model.PreStakingAllocationResettableField{&zero}
miner is processing only UpdatedUser fields here: https://github.com/ice-blockchain/freezer/blob/master/miner/miner.go#L388 but we need those fields from user to reset to zero as well as they're used for balances calculations

2024-01-26 14:47 UTC, ice-myles commented on miner/mining.go
> +		updatedUser.PreStakingAllocationResettableField = model.PreStakingAllocationResettableField{&zero}
And then for [global rank calculation](https://github.com/ice-blockchain/freezer/blob/master/miner/miner.go#L408-L410), but this case will be handled.

2024-01-26 14:57 UTC, ice-myles submitted a review, later dismissed

2024-01-30 13:00 UTC, ice-ares requested changes

2024-01-30 13:00 UTC, ice-ares commented on miner/mining.go
> +	needPrestakingReset := usr.QuizWillBeReset(updatedUser.BalanceLastUpdatedAt)
Anything before this uses those fields u are resetting?

2024-01-30 13:00 UTC, ice-ares commented on model/model.go
> +func (kyc *KYCState) QuizWillBeReset(past *time.Time) bool {
MustDisablePreStaking

2024-01-30 13:00 UTC, ice-ares commented on model/model.go
> +func (kyc *KYCState) QuizWasReset(future *time.Time) bool {
PreStakingAlreadyDisabled

2024-01-30 13:00 UTC, ice-ares commented on model/model.go
> +func (kyc *KYCState) compareQuizReset(cmp func(quizReset *time.Time) bool) bool {
comparePreStakingReset

2024-01-30 13:00 UTC, ice-ares commented on tokenomics/contract.go
> +	ErrPrestakingDisabled                     = errors.New("disabled")
pre-staking disabled

2024-01-30 13:00 UTC, ice-ares commented on tokenomics/pre_staking.go
> +	if !isPrestakingDisabled || (existing != nil && existing.PreStakingAllocation != 0) {
Why allocation!=0 ?

2024-01-30 13:00 UTC, ice-ares commented on tokenomics/pre_staking.go
> +	if !isPrestakingDisabled || (existing != nil && existing.PreStakingAllocation != 0) {
U'll never be able to prestake on a fresh account with that condition

2024-01-30 13:00 UTC, ice-ares commented on miner/mining_test.go
> +	t.Run("balance is accumulated between mine calls", func(t *testing.T) {
Did u test some race conditions? IE prestaking is changed by both the miner and refrigerant at the same time?

2024-01-30 14:00 UTC, ice-cronus commented on tokenomics/pre_staking.go
> +	if !isPrestakingDisabled || (existing != nil && existing.PreStakingAllocation != 0) {
cuz that condition is triggered only if it is disabled (there is OR, it will pass for fresh accounts) OR we need to reset it (and we need to have existing allocation to reset)

2024-01-30 14:00 UTC, ice-cronus commented on miner/mining_test.go
> +	t.Run("balance is accumulated between mine calls", func(t *testing.T) {
I tried it manually to make sure if miner does not overwrite (old) values with new ones provided by refrigerant (that else  = nil and omitempty handles that). But we can try to add it to concurrent test, yea

2024-01-30 14:02 UTC, ice-ares commented on tokenomics/pre_staking.go
> +	if !isPrestakingDisabled || (existing != nil && existing.PreStakingAllocation != 0) {
u are updating db only if pre staking was already set. How exactly does that work for fresh accounts?

2024-01-30 14:06 UTC, ice-cronus commented on miner/mining.go
> +	needPrestakingReset := usr.QuizWillBeReset(updatedUser.BalanceLastUpdatedAt)
Rechecked, prestaking is applied only at the end as it affects standart / pre-staked balance, so nothing before

2024-01-30 14:17 UTC, ice-cronus commented on tokenomics/pre_staking.go
> +	if !isPrestakingDisabled || (existing != nil && existing.PreStakingAllocation != 0) {
by first condition !isPrestakingDisabled ? I just rechecked by hand with debugger and redis-cli I got value, in db, and updated also

2024-01-30 14:25 UTC, ice-cronus commented on miner/mining_test.go
> +	t.Run("balance is accumulated between mine calls", func(t *testing.T) {
Actually it seems we need to have inregration test here. Cuz it relies on omitempty redis field

2024-01-30 14:26 UTC, ice-ares commented on miner/mining_test.go
> +	t.Run("balance is accumulated between mine calls", func(t *testing.T) {
just test it somehow manually and see

2024-01-30 14:32 UTC, ice-cronus commented on miner/mining_test.go
> +	t.Run("balance is accumulated between mine calls", func(t *testing.T) {
Manually I tried 2 approaches:
1) miner have nothing to reset - when user changes pre-staking from endpoint - it is changed (no old values overwritten from miner)
2) user bombs endpoint non-stop (rare case) and miner have to reset it is near-future (~30s) - it is reset && disabled as well (it is hard to decide forom which side, but it seems from last endpoint call)

2024-01-30 14:34 UTC, ice-ares commented on miner/mining_test.go
> +	t.Run("balance is accumulated between mine calls", func(t *testing.T) {
ok, just look over the flow end to end and make sure there are no issues if race conditions happen

2024-01-30 15:29 UTC, merged