sync quiz status from miner
ice-blockchain/freezer pull request #123
Opened 2024-02-12 13:25 UTC by ice-cronus

2024-02-12 13:30 UTC, ice-ares requested changes

2024-02-12 13:30 UTC, ice-ares commented on model/model.go
> +		KYCQuizCompleted *FlexibleBool `json:"kycQuizCompleted" redis:"kyc_quiz_completed,omitempty"`
Why do u need it? Override the field with false, whats the problem?

2024-02-12 13:30 UTC, ice-ares commented on application.yaml
> +quiz:
Move the sql into kyc/quiz. Add a repository (read only) constructor, call the api from miner. Similarly with how coin distribution is called

2024-02-12 13:33 UTC, ice-cronus commented on model/model.go
> +		KYCQuizCompleted *FlexibleBool `json:"kycQuizCompleted" redis:"kyc_quiz_completed,omitempty"`
Dont we need an opportunity to set them to false ( if we'll decide to allow more resets for example)? If not - sure it can be omitempty (to avoid writes if it was not synced on this iteration) with simple bool, but it would be one-way sync

2024-02-12 13:44 UTC, ice-ares commented on model/model.go
> +		KYCQuizCompleted *FlexibleBool `json:"kycQuizCompleted" redis:"kyc_quiz_completed,omitempty"`
Keep it simple for now, basic bool

2024-02-13 10:23 UTC, ice-myles commented on miner/miner.go
> +			for i := range histories {
if len(quizStatuses) > 0 not to execute loop for empty quizStatuses.

2024-02-13 10:33 UTC, ice-myles submitted a review, later dismissed

2024-02-13 12:57 UTC, ice-ares requested changes

2024-02-13 12:57 UTC, ice-ares commented on application.yaml
> +  wintr/connectors/storage/v2: &usersdb
Set only what u need

2024-02-13 12:57 UTC, ice-ares commented on miner/contract.go
> +		userID string
Just move the userid field here

2024-02-13 12:57 UTC, ice-ares commented on model/model.go
> +		KYCQuizCompleted bool `json:"kycQuizCompleted" redis:"kyc_quiz_completed,omitempty"`
Sadly, we're gonna need to be able to change those flags for users to false in some cases, so bring the *bool variant back

2024-02-13 12:57 UTC, ice-ares commented on miner/miner.go
> +				if quizSync, hasQuizSync := quizStatuses[value.userID]; hasQuizSync && quizSync != nil && (quizSync.KYCQuizCompleted || quizSync.KYCQuizDisabled) {
Lets remove that (completed || disabled check) cuz we need to be able to set those flags back to false from true

2024-02-13 12:57 UTC, ice-ares commented on miner/miner.go
> +					if quizSync, hasQuizSync := quizStatuses[histories[i].UserID]; hasQuizSync && quizSync != nil && (quizSync.KYCQuizCompleted || quizSync.KYCQuizDisabled) {
Lets remove that (completed || disabled check) cuz we need to be able to set those flags back to false from true

2024-02-13 12:57 UTC, ice-ares commented on miner/miner.go
> +				if !usr.KYCState.KYCQuizDisabled && !usr.KYCState.KYCQuizCompleted {
Lets remove that check and add only the one that is used ro generate histories every hour, cuz we need to be able to set those flags back to false from true

2024-02-13 12:57 UTC, ice-ares commented on miner/metrics.go
> +	t.steps = [10]string{"mine[full iteration]", "mine", "get_users", "get_referrals", "send_messages", "get_history", "sync_quiz", "insert_history", "collect_coin_distributions", "update_users"} //noli
sync_quiz_status

2024-02-13 15:06 UTC, merged