Feature metrics
ice-blockchain/freezer pull request #124
Opened 2024-02-12 16:32 UTC by ice-dionysos

2024-02-13 00:02 UTC, ice-ares requested changes

2024-02-13 00:02 UTC, ice-ares commented on cmd/freezer/contract.go
> +		tokenomicsDetailedMetricsRepository detailedMetrics.Repository
Actually, now that i think about it. I think u should add the extra info in the existing coin stats endpoint, at the top level (not in the time series)

2024-02-13 00:02 UTC, ice-ares commented on cmd/freezer/contract.go
> +		tokenomicsDetailedMetricsRepository detailedMetrics.Repository
U can use the child aggression deadline to cache what u need to cache, but do a child agg deadline/6 (cuz its 1h on prod)

2024-02-13 00:02 UTC, ice-ares commented on cmd/freezer/contract.go
> +		tokenomicsDetailedMetricsRepository detailedMetrics.Repository
Make the existing endpoint work without authorisation (ask the guys on how to do it)

2024-02-13 00:02 UTC, ice-ares commented on tokenomics/detailed_coin_metrics/repository.go
> +	summary, err := r.TokenomicsRepo.GetTotalCoinsSummary(ctx, 1, 0)
No, i was expecting the other way around, to decorate tokenomics with this package. 

Thats the better approach now that u're reusing the same endpoint

2024-02-13 00:02 UTC, ice-ares commented on tokenomics/detailed_coin_metrics/.testdata/application.yaml
> +  refresh-interval-seconds: 60
No longer needed cuz of the child agg/6 thing

2024-02-14 08:11 UTC, ice-ares requested changes

2024-02-14 08:11 UTC, ice-ares commented on cmd/freezer/contract.go
> -	GetAdoptionArg   struct{}
Rollback

2024-02-14 08:11 UTC, ice-ares commented on tokenomics/detailed_coin_metrics/api_client.go
> +		SetHeader("X-CMC_PRO_API_KEY", key).
Make sure this doesn't appear in logs

2024-02-14 08:11 UTC, ice-ares commented on tokenomics/detailed_coin_metrics/contract.go
> +		UpdatedAt    *time.Time `json:"updatedAt"`
Remove it, its not relevant

2024-02-14 08:25 UTC, ice-ares commented on cmd/freezer/contract.go
> -	GetAdoptionArg   struct{}
I meant the detailed structure u added previously

2024-02-14 08:35 UTC, ice-myles commented on tokenomics/detailed_coin_metrics/repository.go
> +		panic(fmt.Sprintf("unexpected API response: %+v", data))
Is it safe to use panic here?

2024-02-14 08:49 UTC, ice-dionysos commented on tokenomics/detailed_coin_metrics/api_client.go
> +		SetHeader("X-CMC_PRO_API_KEY", key).
It does not. Because it is inside the headers.

2024-02-14 14:35 UTC, ice-dionysos commented on tokenomics/detailed_coin_metrics/repository.go
> +		panic(fmt.Sprintf("unexpected API response: %+v", data))
I would say yes, we *must* have that id/quote here.

2024-02-14 14:38 UTC, ice-ares commented on tokenomics/balance_total_coins.go
> +	res.BlockchainDetails = details
no, just return err

2024-02-14 14:39 UTC, ice-ares commented on tokenomics/balance_total_coins.go
> +	vals, err := storage.Get[BlockchainDetails](ctx, r.db, totalCoinStatsDetailsKey, totalCoinStatsDetailsKey)
why u getting the same hash twice?

2024-02-14 15:25 UTC, merged