Fixed referrals count increase/decrease when an user was deleted.
ice-blockchain/freezer pull request #17
Opened 2023-07-10 22:51 UTC by ice-myles

Fixed referrals count increase/decrease when an user was deleted.

2023-07-11 05:47 UTC, ice-ares commented on tokenomics/users.go
> +			if dbUser[0].MiningSessionSoloEndedAt != nil && dbUser[0].MiningSessionSoloEndedAt.After(*time.Now().Time) {
! .IsNil

2023-07-11 05:48 UTC, ice-ares commented on tokenomics/users.go
> +					if err = s.db.HIncrBy(ctx, idT0Key, "active_t1_referrals", 1).Err(); err != nil {
Whar about the t1 active users of the user?

2023-07-11 07:38 UTC, ice-myles commented on tokenomics/users.go
> +					if err = s.db.HIncrBy(ctx, idT0Key, "active_t1_referrals", 1).Err(); err != nil {
The idea that **each** new IDT0 and IDTMinus1 gets increment at own updateReferredBy.

Example:
```
User A had 10 t1, 20 t2
User B (referred_by = A)
User C (referred_by = B)
User D (referred_by = B)
```

If to run mining for A,B,C,D:
```
A has 2 active t2
B has 2 active t1
```

We remove user B.

```
A gets -1 to active_t1(B) and -2 to active_t2 (C,D).
```

Then updateReferredBy is called for each user who need to get update (it's C,D users)
For example theirs new IDT0 and IDTMinus1 are E,F:
```
E -> F -> C,D
```

Then we have updateReferredBy for C:
```
F gets +1 active_t1
E gets +1 active_t2
```

updateReferredBy for D:
```
F gets +1 active_t1
E gets +1 active_t2
```

Now:
```
F has 2 active_t2
E has 2 active_t1
```

2023-07-13 20:21 UTC, ice-ares requested changes
Too many unnecessary changes

2023-07-13 20:21 UTC, ice-ares commented on miner/contract.go
> +		ID, oldIDT0, oldIDTMinus1, newIDT0, newIDTMinus1 int64
Why do u need old one? It doesnt matter, old one is deleted

2023-07-13 20:21 UTC, ice-ares commented on miner/contract.go
> +		model.IDT0Field
Why do u need this?

2023-07-13 20:21 UTC, ice-ares commented on miner/contract.go
> +		model.IDTMinus1ForT2UpdateInitiatedAtField
Why do u need this?

2023-07-13 20:21 UTC, ice-ares commented on miner/miner.go
> +				if userWithUpdatedReferredBy := wasReferredByUpdated(usr); userWithUpdatedReferredBy != nil {
No. Use the referral life cycle part. U have everything there.

2023-07-13 20:21 UTC, ice-ares commented on miner/referral_lifecycle.go
>  func changeT0AndTMinus1Referrals(usr *user) {
U can make this return 2 flags: t0 changed, tminua1 changed. And reuse it

2023-07-13 20:55 UTC, ice-myles commented on miner/contract.go
> +		ID, oldIDT0, oldIDTMinus1, newIDT0, newIDTMinus1 int64
I need some flag to understand that user state was changed. As user deletion/updating referredBy are done at the tokenomics processor, then I need to know in miner what is the old and what is the new state to do smth by condition. This condition is compare old and new values.

2023-07-13 20:56 UTC, ice-myles commented on miner/contract.go
> +		model.IDTMinus1ForT2UpdateInitiatedAtField
Because we need to update IDTminus1 for each T2 of updated user. This process should be initiated after change from old to new ids.

2023-07-13 20:57 UTC, ice-myles commented on miner/contract.go
> +		model.IDT0Field
Right, it's not needed.

2023-07-13 21:01 UTC, ice-myles commented on miner/miner.go
> +				if userWithUpdatedReferredBy := wasReferredByUpdated(usr); userWithUpdatedReferredBy != nil {
I tried this option. But okay, how would you understand that you have changed ids using this? What is the condition? old and new referrals. But how to gather them in miner if update is in the tokenomics? We need to know old and new at some stage.

2023-08-03 01:36 UTC, ice-ares commented on miner/contract.go
> +	IDsOnlyUpdatedUser struct {
referralsUpdated

2023-08-03 01:43 UTC, ice-ares commented on miner/mining.go
> +func updateT0AndTMinus1ReferralsForUserHasNeverMined(usr *user) (updatedUser *IDsOnlyUpdatedUser, IDT0Changed bool) {
u dont need 2 return values. Use nil instead of bool

2023-08-03 01:45 UTC, ice-ares commented on miner/mining.go
> +	IDT0Changed, _ = changeT0AndTMinus1Referrals(updatedUser, false)
Why dont u reset it?

2023-08-03 01:47 UTC, ice-ares commented on miner/miner.go
> +			for id, value := range t1ReferralsToIncrementActiveValue {
Move these 2 before the ones that decrement those fields

2023-08-03 01:49 UTC, ice-ares commented on miner/miner.go
> +					if usr.IDTMinus1 != t0Ref.IDT0 {
Why would they be different?

2023-08-03 01:52 UTC, ice-ares commented on miner/referral_lifecycle.go
> +func changeT0AndTMinus1Referrals(usr *user, reset bool) (IDT0Changed, IDTMinus1Changed bool) {
Why do u need rhat reset flag?

2023-08-03 01:53 UTC, ice-ares commented
Fix tests and add more  to test changes u made

2023-08-03 07:36 UTC, ice-myles commented on miner/miner.go
> +					if usr.IDTMinus1 != t0Ref.IDT0 {
Because there is the case when user A has t1 B and t2 C.
User A was deleted. B gets new IDT0 - E. His IDTMinus1 is changed properly.
But user's C IDTMinus1 was not changed (I would say more: A can have C,D,F,G,H,.... t2 and theirs IDTMinus1 is not changed in this case), so I need to change IDTMinus1 for t2 manually.

2023-08-03 07:38 UTC, ice-myles commented on miner/referral_lifecycle.go
> +func changeT0AndTMinus1Referrals(usr *user, reset bool) (IDT0Changed, IDTMinus1Changed bool) {
Because reset to 0 is needed for active users, for not active I don't need to reset. Though anyway I use then another structure, so need to rollback this.

2023-08-04 13:57 UTC, merged