Feature/implement start mining
ice-blockchain/freezer pull request #3
Opened 2022-04-22 14:02 UTC by azayats-leftclick

2022-04-22 14:26 UTC, antonh21 commented on application.yaml
> +    port: 8443
No need to change port at the configuration file for the repo. Is enough to change locally if you run tests on your own port.

2022-04-22 14:46 UTC, antonh21 commented on Makefile
> +	`go env GOROOT`/bin/addlicense -f LICENSE.header * .github/*
Why is here `GOROOT` indstead of `GOPATH`?

2022-04-22 14:54 UTC, azayats-leftclick commented on Makefile
> +	`go env GOROOT`/bin/addlicense -f LICENSE.header * .github/*
in my case, the command `go install github.com/google/addlicense@latest` installs addlicense to GOROOT
may be i've missed something

2022-04-22 14:56 UTC, antonh21 commented on economy/economy.go
> +		return nowNano, errors.Wrapf(err, "failed set last_mining_started_at for userID:%v", userID)
When error occurs no need to return the data, only error.
```
return nil, errors.Wrapf(err, "failed set last_mining_started_at for userID:%v", userID)
```

2022-04-22 15:06 UTC, azayats-leftclick commented on economy/economy.go
> +		return nowNano, errors.Wrapf(err, "failed set last_mining_started_at for userID:%v", userID)
uint64 can't be nil, sorry

2022-04-25 21:59 UTC, antonh21 commented on Makefile
> +	`go env GOROOT`/bin/addlicense -f LICENSE.header * .github/*
Nevertheless for the PR you should do rollback. This repo was created from template that is configured for the CI/CD.

2022-04-25 21:59 UTC, antonh21 commented on Makefile
> +	`go env GOROOT`/bin/addlicense -f LICENSE.header * .github/*
Nevertheless for the PR you should do rollback. This repo was created from template that is configured for the CI/CD.

2022-04-25 22:00 UTC, antonh21 commented on application.yaml
> +    consumerGroup: freezer-economy
`freezer-refrigerant-testing` will be here as at get user economy endpoint.

2022-04-25 22:00 UTC, antonh21 commented on application.yaml
> +    consumerGroup: freezer-economy
`freezer-refrigerant-testing` will be here as at get user economy endpoint.

2022-04-25 22:01 UTC, antonh21 commented on economy/fixture/.testdata/application.yaml
> +# SPDX-License-Identifier: BUSL-1.1
This file and all folder `.testdata` is not needed, it can be removed.

2022-04-25 22:01 UTC, antonh21 commented on economy/fixture/.testdata/application.yaml
> +# SPDX-License-Identifier: BUSL-1.1
This file and all folder `.testdata` is not needed, it can be removed.

2022-04-25 22:05 UTC, antonh21 commented on economy/contract.go
> +		UserID UserID `json:"user_id"`
`json:"userId"`. camelCase for a json field name.

2022-04-26 06:53 UTC, victor-oancea-leftclick-io commented on Makefile
> +	`go env GOROOT`/bin/addlicense -f LICENSE.header * .github/*
You need gopath for installing binaries, not goroot

2022-04-28 13:17 UTC, victor-oancea-leftclick-io requested changes

2022-04-28 13:17 UTC, victor-oancea-leftclick-io commented on economy/start_mining.go
> +	nowNano := uint64(time.Now().UnixNano())
always UTC()

2022-04-28 13:17 UTC, victor-oancea-leftclick-io commented on economy/start_mining.go
> +func (r *userEconomyRepository) StartMining(ctx context.Context, userID UserID) error {
you just have to handle it in the endpoint

2022-04-28 13:17 UTC, victor-oancea-leftclick-io commented on economy/start_mining.go
> +		return false, errors.Wrapf(nil, "unable to find record for UserID:%v", userID)
wrapf(storage.ErrNotFound

2022-04-28 13:48 UTC, azayats-leftclick commented on cmd/freezer-refrigerant/economy.go
> +		return server.Response{
this approach do not give us to return 409 on mining in progress

2022-04-28 14:09 UTC, victor-oancea-leftclick-io commented on cmd/freezer-refrigerant/economy.go
> +		return server.Response{
```

if errors.Is(err, economy.ErrMiningInProgress) {
 	return server.Response{
 	Code: code,
 			Data: server.ErrorResponse{
 				Error: err.Error(),
 				Code:  "MINING_IN_PROGRESS",
 			}.Fail(err)),
 		}
}
```

2022-04-28 14:55 UTC, azayats-leftclick commented on economy/start_mining.go
> +func (r *userEconomyRepository) StartMining(ctx context.Context, userID UserID) error {
How It is can be possible?
We perform this action with authorised user

2022-04-28 16:18 UTC, victor-oancea-leftclick-io commented on cmd/freezer-refrigerant/freezer_refrigerant.go
> +	s.economyRepository = economy.New(ctx, cancel)
:))) @azayats-leftclick you removed the good one

2022-05-04 07:28 UTC, kfedor commented on cmd/freezer-refrigerant/economy.go
> +		if errors.Is(err, economy.ErrMiningInProgress) {
imho switch without expression might look better, help to save lines, like:

switch {
    case errors.Is( err, .... ): 
           return 
    case errors.Is( ......:
           return
}

2022-05-04 07:31 UTC, kfedor commented on cmd/freezer-refrigerant/economy.go
> +	return server.Response{
we use such response a lot in different projects
perhaps we should add a wrapper to Wintr ?

and do return getServerErrorResponse( )

func getServerErrorResponse(httpCode int, err error, code string) server.Response {
	return server.Response{
		Code: httpCode,
		Data: server.ErrorResponse{
			Error: err.Error(),
			Code:  code,
		}.Fail(err),
	}
}

2022-05-04 11:40 UTC, azayats-leftclick commented on cmd/freezer-refrigerant/economy.go
> +		if errors.Is(err, economy.ErrMiningInProgress) {
done

2022-05-04 11:51 UTC, kfedor approved these changes

2022-05-04 15:37 UTC, victor-oancea-leftclick-io commented on economy/contract.go
> +		UserID UserID    `json:"userId"`
u don't need this, userID is the message key

2022-05-04 15:45 UTC, azayats-leftclick commented on economy/contract.go
> +	"errors"
done

2022-05-04 15:45 UTC, azayats-leftclick commented on cmd/freezer-refrigerant/freezer_refrigerant.go
> -	if err := s.economyProcessor.CheckHealth(ctx); err != nil {
done

2022-05-04 15:46 UTC, victor-oancea-leftclick-io approved these changes

2022-05-04 15:48 UTC, kfedor approved these changes

2022-05-04 16:05 UTC, merged