t1/t2 balance, t1/t2 active counts recalculations.
ice-blockchain/freezer pull request #33
Opened 2023-10-12 16:28 UTC by ice-myles

### The problem

Due to bugs that were fixed after the app release launch, part of the users have got the wrong T1/T2 balances calculations. For example one of the bugs: when some user removed his account, his T1, T2 didn't get the T1/T2 active referrals change in proper way. 
To reduce the inequality we must set the right T1/T2 balances (as all other balances were not affected) for everybody so that everyone is on equal terms.

### The solution

To recalculate balances we should get active ranges for each user and correlate them with active ranges of T1/T2. 

For example:
```
T0 = user1
T1 = user2
...
TN = userN (T1)
```

user1 (T0) active time ranges from clickhouse:
```
2023/10/12 14:49:37.593809 - 2023/10/12 14:51:37.593809 (2 min) 
2023/10/12 14:52:50.593809 - 2023/10/12 14:53:50.593809  (1 min)
```

user2 (T1) active time ranges from clickhouse:
```
2023/10/12 14:49:45.593809 - 2023/10/12 14:51:45.593809 (2 min)
2023/10/12 14:52:37.593809 - 2023/10/12 14:53:37.593809 (1 min)
```

So user1 ranges are crossed with user2 (T1):
```
2023/10/12 14:49:45.593809 - 2023/10/12 14:51:37.593809 (1 min 52 sec of joint activity for the first ranges)
2023/10/12 14:52:50.593809 - 2023/10/12 14:53:37.593809 (47 sec of joint activity for the second ranges)
etc
```
Then user1 ranges are crossed with all separate users from T1 to TN
Also the same is done for T2 users to get crossing time ranges and use active time ranges to recalculate balances.

**Slashing**

For the slashing case we need to know only when T0 (user for whom we recalculate T1/T2 balances) wasn't active (when his slashing_solo_rate > 0). In this case everything related to slashing does mine() function and more specifically it just set slashing rates and each elapsed time decrease the balances by slashing rate.

Only 1 additional thing that should be known here about implementation: `created_at` field from the clickhouse history is used for slashing calculations and last value (`created_at`) is always "rounded", it means it has values like 12:00, 13:00, 14:00, etc. Then when the slashing is finished and new mining session is started, we just need to slash time diff between `mining_session_solo_started_at` and `created_at`.

For example new mining session started at 12:37, then we need to slash last 37 minutes in the last history record before new mining session, and next 23 minutes are used then for the positive balances calculations.

**Streaks and day offs**

They are taken into the account. As theirs implementation assumes that several `mining_session_solo_started_at` fields can have the same value (due to streaks), this case is handled not to take into account the repeated time ranges. The implementation has the `previousUserStartedAt`, `previousUserEndedAt`, `previousT1MiningSessionStartedAt`, `previousT1MiningSessionEndedAt`, `previousT2MiningSessionStartedAt`, `previousT2MiningSessionEndedAt` variables to use them for streaks and day-offs detection.

**Resurrect**

Resurrection is done not through `mine()` function (as it was difficult to pass right time points) but by separate flag in the recalculations. If resurrect was happened for an user, just boolean flag is set to true, t1/t2 balances is being resurrected, and then resurrection is not repeated more for this user.

**Adoption switch among the crossing time ranges**

As base mining rate (BMR) can be changed, we need to take this change into the account while recalculating. For this case implementation sends the start and end values of the range to the `splitByAdoptionTimeRanges` function. This function splits the time range by adoptions values, for example:
```
N    timePoint                    BMR
---------------------------------------
1     2023/10/12 14:49:45.593809, 16
2     2023/10/12 14:49:57.593809,  8
3     2023/10/12 14:50:32.593809,  4
4     2023/10/12 14:51:37.593809,  2
```
The time between start and end as a rule is the time from `AchievedAt` field of adoptions (if any adoption switch is happened between this range).
So each (time point - previous time point) must be calculated with it's own BMR.
NOTE: The function all the time returns _start_ and _end_ time points with theirs actual adoptions.

**New users while balances are recalculated**

For new users while balances are recalculated `recalculated` key will be added as we don't need to recalculate anything for them (they were created after bugfixing).

**The difference between actual and recalculated values problem**

The difference between t1/t2 calculated and t1/t2 actual balances will be all the time due to `mine()` function calculates balances based on small pieces of time when some `active_t1_referrals`/`active_t2_referrals` could have been already  decreased.
More details for the understanding: each user has `active_t1_referrals` and `active_t2_referrals` fields. For example user0 has:
```
active_t1_referrals = 10
active_t2_referrals = 5
```
when mine() function is called. The small piece of time, when balances are recalculated, use these values to multiply with T1/T2 coefficients and elapsed time (for example 40 ms). But 1 of 10 active t1 could stop be active after 20 ms from these 40 ms, though 20 ms are still used for the multiplying. So these small pieces of time can add balance a bit.

This balance recalculation implemenation has more accuracy as it is kept on exact time ranges from the history, but not on the T1/T2 active counts.

**When is better to use recalculations**

Recalculations is better to use at the beginning of the hour/minute for production/staging as here history has the fresh update.
For example if recalculation was launched at 11:58, and new history records will be appeared at 12:00 only, then this last hour will not be taken into the account.

**Balances backup mode**

When the balances are recalculated the first time, then the old t1/t2 balances (t1/t2 slashing rates and t1/t2 active counts) need to be stored to have possibility to restore them .
`balances_backup_mode` key should be added with value `true` to restore all stuff that was before recalculation. If to save not true (anything another) - it will work in recalculation mode.

_NOTE:_ if 1 day passed from the time point when recalculation was started and then backup was used, the balances for this day will not be restored.

**Actualise santa**

`update_santa_badges_levels_and_roles_tasks` script actualises data in santa database.
If balance/friends invited were changed after the recalculations, then need to be changed friends invited/balance/socials/levels/roles/badges/etc fields in santa.

**Actualise eskimo**

Several fields in eskimo have the inequality, so we need to make them actual as well. For this is enough to update T1/T2 values in the `referral_acquisition_history` table.

Update t1/t2 values
```
WITH t2_table AS (
    SELECT
       SUM(1) as t2_count,
       u.id
  FROM users u
    JOIN USERS t1
       ON t1.referred_by = u.ID
              AND t1.id != u.id
              AND t1.username != t1.id
              AND t1.referred_by != t1.id
    JOIN USERS referrals
      ON referrals.referred_by = t1.ID
            AND referrals.id != t1.id
            AND referrals.username != referrals.id
            AND referrals.referred_by != referrals.id
  GROUP BY u.id
 ),
 calculated AS (
    SELECT 
       u.id AS id,
       COUNT(t1.id) AS t1_count,
       COALESCE(t2_count, 0) AS t2_count
  FROM users u
      LEFT JOIN t2_table
          ON t2_table.id = u.id
      LEFT JOIN USERS t1
          ON t1.referred_by = u.id
                 AND t1.username != t1.id
                 AND t1.referred_by != t1.id
  GROUP BY u.id, t2_count
)
UPDATE referral_acquisition_history rah
     SET t1 = calculated.t1_count,
            t2 = calculated.t2_count
  FROM calculated
  WHERE rah.user_id = calculated.id
```

T1 check
```
WITH t1_table AS (
   SELECT 
       COUNT(*) AS t1_count, u.referred_by AS id
   FROM users u
       JOIN USERS referrals
                ON (u.referred_by = referrals.id) [...]

2023-10-13 11:45 UTC, ice-cronus requested changes

2023-10-13 11:45 UTC, ice-cronus commented on miner/miner.go
> +				userKeys = append(userKeys, model.SerializedRecalculatedUsersKey((workers*ix)+workerNumber))
I think u need extra variable for recalculated keys, cuz userKeys is being used [here](https://github.com/ice-blockchain/freezer/blob/master/miner/miner.go#L142) to understand if all batch is processed. But in your case, you can have much less recalculations than total batch (or zero at all on first run)

2023-10-13 11:45 UTC, ice-cronus commented on miner/recalculate_balance.go
> +		WHERE referred_by = ANY($1)
I think type cast for input is missing.

2023-10-13 11:45 UTC, ice-cronus commented on miner/recalculate_balance.go
> +		UNION
UNION ALL would be faster if u dont need uniqueness

2023-10-13 11:45 UTC, ice-cronus commented on miner/miner.go
> +		recalculatedTiersBalancesUsers, err := m.showTiersDiffBalances(ctx, userResults, userRecalculatedResults, tMinus1Referrals, t0Referrals)
Do we really need to keep re-checking logic? It makes sense to add a flag / something like that, cuz it seems it would apply (and get data from eskimo, etc) for every new user, isn't it? Current ones are marked as recalculated and excluded, but new ones will appear and they will never get recalculated flag and will be processed again and again

2023-10-13 11:45 UTC, ice-cronus commented on miner/recalculate_balance.go
> +					updatedUser = initializeEmptyUser(updatedUser, usr)
How it could be nil? Would not we reinitialize and update state for deleted users this way (they're still presented in history)?

2023-10-13 11:45 UTC, ice-cronus commented on miner/recalculate_balance.go
> +					if timeDiff >= 60*stdlibtime.Hour {
60 hours? Isn't it 24, but actually it comes from cfg

2023-10-13 11:45 UTC, ice-cronus commented on cmd/scripts/update_santa_badges_levels_and_roles_tasks/update_santa_badges_levels_and_roles_tasks.go
> +				userKeys = append(userKeys, model.SerializedUsersKey((workers*ix)+workerNumber))
Do we need to fetch all the users? Isn't it better to rely on recalculated keys only previuosly created by miner? Or we need to keep them independent?

2023-10-13 11:45 UTC, ice-cronus commented on cmd/scripts/update_santa_badges_levels_and_roles_tasks/update_santa_badges_levels_and_roles_tasks.go
> +		_, err := storagePG.Exec(ctx, u.dbSanta, sql, usr.UserID, usr.ActualFriendsInvited, enabledRoles)
I think we can update friends-invited first, and then rely on that updated data in other tables (levels, roles, badges, tasks) it will simplify the code, and you will not need to manually fetch the data

2023-10-13 11:45 UTC, ice-cronus commented on cmd/scripts/update_santa_badges_levels_and_roles_tasks/update_santa_badges_levels_and_roles_tasks.go
> +func (u *updater) reEvaluateEnabledRole(friendsInvited uint64) *users.Enum[levelsandroles.RoleType] {
may be to update santa w/ making this functions public and just import them?

2023-10-13 12:18 UTC, ice-myles commented on miner/recalculate_balance.go
> +					updatedUser = initializeEmptyUser(updatedUser, usr)
mine() function can return nil, so it can be nil here when all balance slashed (when updatedUser.isAbsoluteZero()), and then when user started mining again we need to reinitialize him.

2023-10-13 12:25 UTC, ice-myles commented on miner/recalculate_balance.go
> +					if timeDiff >= 60*stdlibtime.Hour {
No, this is needed to reset user to absolute zero when slashing is finished. As history is not added then, some non null value is still shown. This is like a hack to reset value when no more history available.
But seems like it's still bug from my side as slashing rate for production is calculated as:
```
updatedUser.BalanceT1 / 60. / miningSessionRatio
```
where miningSessionRatio for production is 24, 1 for staging. It means 60 days (not 60 hours) to slash all balance.

2023-10-13 12:26 UTC, ice-myles commented on cmd/scripts/update_santa_badges_levels_and_roles_tasks/update_santa_badges_levels_and_roles_tasks.go
> +				userKeys = append(userKeys, model.SerializedUsersKey((workers*ix)+workerNumber))
It's to update all available users by actual friends_invited (and consequently badges/levels/roles/etc), not only to update balances.

2023-10-13 12:28 UTC, ice-myles commented on cmd/scripts/update_santa_badges_levels_and_roles_tasks/update_santa_badges_levels_and_roles_tasks.go
> +func (u *updater) reEvaluateEnabledRole(friendsInvited uint64) *users.Enum[levelsandroles.RoleType] {
Maybe it is better to move the script to santa, as it has more santa data update. Then yes, otherwise I didn't want to create separate PR for such a small thing.

2023-10-13 12:40 UTC, ice-myles commented on miner/miner.go
> +		recalculatedTiersBalancesUsers, err := m.showTiersDiffBalances(ctx, userResults, userRecalculatedResults, tMinus1Referrals, t0Referrals)
Actually we need to keep this logic. But question about new users is right. Maybe it worth as a hack during this time (while commit deployed) to create recalculated keys with needed data for all new users, not to recalculate them.
As to get recalculation they need to have at least 1 tier and at least 1 history record for user and tier. Theoretically they can be recalculated in this time range, so is better to restrict.

2023-10-13 12:45 UTC, ice-cronus commented on cmd/scripts/update_santa_badges_levels_and_roles_tasks/update_santa_badges_levels_and_roles_tasks.go
> +				userKeys = append(userKeys, model.SerializedUsersKey((workers*ix)+workerNumber))
It's not about mining, but friends invited. Those `recalculated` users contains users with `active` referrals count change, but friends-invited contains `all` referrals

2023-10-19 14:23 UTC, ice-ares requested changes

2023-10-19 14:23 UTC, ice-ares commented on miner/DDL.sql
> +CREATE TABLE IF NOT EXISTS users  (
Move this in .testdata

2023-10-19 14:23 UTC, ice-ares commented on miner/DDL.sql
> +CREATE TABLE IF NOT EXISTS users  (
Actually remove it, and use the link to eskimo/users/ddl.sql

2023-10-19 14:23 UTC, ice-ares commented on miner/contract.go
> +	ddl string
Not needed

2023-10-19 14:23 UTC, ice-ares commented on miner/metrics_test.go
> +func TestGetAdoptionsRange_1AdoptionPerRange(t *testing.T) {
Has nothing to do with metrics, move to separate file

2023-10-19 14:23 UTC, ice-ares commented on bookkeeper/storage/storage.go
> +						   WHERE id IN [%[2]v]
prepared statement

2023-10-19 14:23 UTC, ice-ares commented on bookkeeper/storage/storage.go
> +						   ORDER BY created_at ASC
u`re gonna get a lot of rows without limit

2023-10-19 14:23 UTC, ice-ares commented on miner/miner.go
> +			log.Panic(errors.Wrapf(err, "[miner] failed to get users for batchNumber:%v,workerNumber:%v", batchNumber, workerNumber))
failed to get recalculated users

2023-10-19 14:23 UTC, ice-ares commented on miner/miner.go
> +					// Uncomment to adjust t1/t2 balances and t1/t2 active counts.
No. thats not how that works.

We deploy the code, we wait for all users to get fixed (which means it can run the logic for the same users multiple times, which should be idempotent and not mess up the data if that happens). We rollback the changes. This is not a feature toggle.

2023-10-19 14:23 UTC, ice-ares commented on tokenomics/users.go
> +		RecalculatedTiersBalancesAtField: model.RecalculatedTiersBalancesAtField{RecalculatedTiersBalancesAt: time.Now()},
u might want to use created at, if created at is after the bugfix date

2023-10-19 14:23 UTC, ice-ares commented on miner/recalculate_balance.go
> +		info := fmt.Sprintf("%v,%v,%v,%v,%v,%v,%v,%v,%v,%v,%v", usr.ID, balanceT1Diff, balanceT2Diff, usr.ActiveT1Referrals, usr.ActiveT2Referrals, usr.BalanceT1, usr.BalanceT2, actualBalancesT1[usr.ID], a
watch out for spamming on production data

2023-10-24 08:34 UTC, merged