Feature coin distribution
ice-blockchain/freezer pull request #46
Opened 2023-12-08 17:44 UTC by ice-dionysos

2023-12-11 11:00 UTC, ice-ares requested changes

2023-12-11 11:00 UTC, ice-ares commented on cmd/freezer-coin-distributer/freezer_coin_distributer.go
> +	s.coinDistributer = coindistribution.MustStartCoinDistribution(ctx, cancel, coindistribution.MustNewEthClient(ctx))
Nope, the client is encapsulated in the coindistribution package

2023-12-11 11:00 UTC, ice-ares commented on coin-distribution/client.go
> +	if err != nil {
Unnecessary if

2023-12-11 11:00 UTC, ice-ares commented on coin-distribution/client.go
> +	if err != nil {
Unnecessary if

2023-12-11 11:00 UTC, ice-ares commented on coin-distribution/client.go
> +	return ec.dropper.AirdropToWallets(opts, recipients, amounts) //nolint:wrapcheck //.
ec.airdropper

2023-12-11 11:00 UTC, ice-ares commented on coin-distribution/coin_distribution.go
> +FOR UPDATE SKIP LOCKED
Why skip locked?

2023-12-11 11:00 UTC, ice-ares commented on coin-distribution/coin_distribution.go
> +		return nil, errors.Wrapf(errNotEnoughData, "fetched %v record(s), but want minimum %v", len(result), cd.conf.BatchSizeMin)
Min is Max. We need exactly X rows. Its not a range

2023-12-11 11:00 UTC, ice-ares commented on coin-distribution/coin_distribution.go
> +	opts.Nonce = big.NewInt(int64(nonce))
Any other ops we might set?

2023-12-11 11:00 UTC, ice-ares commented on coin-distribution/coin_distribution.go
> +	cd.mu.Lock()
Huh? Why?

2023-12-11 11:00 UTC, ice-ares commented on coin-distribution/contract.go
> +	"time"
No. We never use this, unless we have to

2023-12-11 11:00 UTC, ice-ares commented on coin-distribution/contract.go
> +	EthClient interface {
Hide this

2023-12-11 11:00 UTC, ice-ares commented on coin-distribution/contract.go
> +	CoinDropper interface {
Hide this

2023-12-11 11:00 UTC, ice-ares commented on coin-distribution/internal/ICEToken.flatten.sol
> +
Can we fetch this from url?

2023-12-11 15:53 UTC, ice-dionysos commented on coin-distribution/internal/ICEToken.flatten.sol
> +
I would prefer the local copy. Fetching new contract on each `generate` can break some API/ABI .

2023-12-11 15:56 UTC, ice-dionysos commented on coin-distribution/coin_distribution.go
> +FOR UPDATE SKIP LOCKED
Do not wait for other rows if they are busy/taken in another transaction.

2023-12-11 17:09 UTC, ice-ares commented on coin-distribution/internal/ICEToken.flatten.sol
> +
Thats the whole point, to break the api if its outdated

2023-12-12 08:07 UTC, ice-dionysos commented on coin-distribution/internal/ICEToken.flatten.sol
> +
If you break it, you'll just lose the transaction amount + fee. You never know from the Ethereum API is that contract valid or not.  It will just create and execute the transaction.

So that's why I would keep it locally.

2023-12-12 08:33 UTC, ice-ares commented on coin-distribution/internal/ICEToken.flatten.sol
> +
No, the code has to be in a single place, when u compile it, u get it from url(github repo). We will not have  the contract in 2 separate repos

2023-12-12 09:05 UTC, ice-dionysos commented on coin-distribution/internal/ICEToken.flatten.sol
> +
Well, let it be then.

2023-12-18 08:44 UTC, ice-ares requested changes

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/DDL.sql
> +        create type pending_coin_distributions_status AS ENUM ('NEW', 'PENDING', 'ACCEPTED', 'REJECTED');
Whats the difference between new and pending?

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/contract.go
> +		CreatedAt  time.Time  `db:"created_at"`
*time.Time

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/contract.go
> +		InternalID int64      `db:"internal_id"`
Move this after strings

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/contract.go
> +		DB           *storage.DB
Remove this

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/contract.go
> +		DB            *storage.DB
Remove this

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/contract.go
> +	txStatus string
Move this to the top of the type (...) definition

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/contract.go
> +	batchMaxSizeLimit = 29_890_000
Seems like a random number. What's that?

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/contract.go
> +		EthStatus  string     `db:"eth_status"`
EthStatus txStatus

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/contract.go
> +		ID      string
Whats this?

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/internal/Makefile
> +
Add a step to check for git changes . Similar like in root makefile

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/processor.go
> +	log.Debug(fmt.Sprintf("starting [%d] worker(s) ...", proc.Conf.Workers))
Log.Info

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/processor.go
> +		eth_status = 'NEW' and
Oh, now i see. U're going for a queue

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/processor.go
> +		created_at ASC
Theoretically, u could end up with the same user id twice, from 2 different days. Would that be a problem for the flow?

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/processor.go
> +	records_count.num = $2 and
Why do u need this check?

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/processor.go
> +		if err = proc.BatchMarkRejected(ctx, num, data); err != nil {
U're doing that for any error? Dont u have some errors that u can retry?

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/processor.go
> +	defer log.Debug(fmt.Sprintf("worker [%v]: stopped", num))
Log info

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/processor.go
> +				log.Warn(fmt.Sprintf("worker [%v]: signal channel is full", num))
Why not block it?

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/processor.go
> +			log.Debug(fmt.Sprintf("worker [%v]: %v", num, ctx.Err()))
Log info

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/processor.go
> +			log.Debug(fmt.Sprintf("worker [%v]: exit signal", num))
Log jnfo

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/processor.go
> +				log.Debug(fmt.Sprintf("worker [%v]: coinDistributer is disabled or blocked", num))
Log info

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/processor.go
> +	return (proc.Conf.StartHours < proc.Conf.EndHours && (currentHour < proc.Conf.StartHours || currentHour > proc.Conf.EndHours)) ||
This condition is only for starting work btw, not finishing it. U can go outside of that interval to finish pending records

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/processor.go
> +	log.Debug("waiting for workers to stop ...")
Info

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/tracker.go
> +		workersMax = 100
Static? Does it scale with something?

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/tracker.go
> +group by
Why ? U dont have any aggregation

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/tracker.go
> +	const stmt = `delete from pending_coin_distributions where (eth_status = 'ACCEPTED' or eth_status = 'PENDING') and eth_tx = any($1)`
Why pending?

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/tracker.go
> +	(eth_status = 'ACCEPTED' or eth_status = 'PENDING') and
Why pending?

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/tracker.go
> +	(eth_status = 'ACCEPTED' or eth_status = 'PENDING') and
Why pending?

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/tracker.go
> +			log.Panic(err, "subscription error")
Why panic?

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/tracker.go
> +			log.Debug("stopping listener due to cancel signal")
Info

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/tracker.go
> +			log.Debug("stopping listener due to context cancellation/error")
Info

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/tracker.go
> +	log.Debug("started listening for new blocks ...")
Info

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/coin_distribution.go
> -func (cd *coinDistributer) distributeCoins(ctx context.Context, workerNumber int64) {
Does ur logic work like this one?

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/coin_distribution.go
> +	db := storage.MustConnect(ctx, ddl, applicationYamlKey)
Dont start a million pools. Just one. And share it to all structs u need

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/coin_distribution.go
> +		errors.Wrap(cd.DB.Close(), "failed to close db"),
This should be closed last

2023-12-18 08:44 UTC, ice-ares commented on coin-distribution/coin_distribution.go
> +	return errors.Wrap(cd.DB.Ping(ctx), "[health-check] failed to ping DB")
Do u need to check the health of the other clients u have?

2023-12-18 08:54 UTC, ice-dionysos commented on coin-distribution/DDL.sql
> +        create type pending_coin_distributions_status AS ENUM ('NEW', 'PENDING', 'ACCEPTED', 'REJECTED');
- `NEW` - database entry was created, but not processed yet.
- `PENDING` - entry in scheduled for execution

2023-12-18 08:54 UTC, ice-dionysos commented on coin-distribution/contract.go
> +		CreatedAt  time.Time  `db:"created_at"`
Why ? It's `NOT NULL` in the schema.

2023-12-18 08:58 UTC, ice-dionysos commented on coin-distribution/contract.go
> +	batchMaxSizeLimit = 29_890_000
This is the maximum number of recipients for one single Airdrop() call. We got it in testing.

2023-12-18 09:05 UTC, ice-dionysos commented on coin-distribution/contract.go
> +		ID      string
For now - just for internal tracking and logs.

2023-12-18 09:09 UTC, ice-dionysos commented on coin-distribution/processor.go
> +		created_at ASC
I'll check that thing, this was made before introducing `day`.

2023-12-18 09:12 UTC, ice-dionysos commented on coin-distribution/processor.go
> +	records_count.num = $2 and
I wanted to check that we have exactly `BatchSize` records from the database. If not, then do nothing. 
From my perspective, it's better than fetching like half of the `BatchSize` from the database, checking its size/len from go code, and then reverting the transaction.

2023-12-18 09:15 UTC, ice-dionysos commented on coin-distribution/processor.go
> +				log.Warn(fmt.Sprintf("worker [%v]: signal channel is full", num))
I prefer to skip that tick, since the worker may be busy with another task or a long-waiting transaction.

2023-12-18 09:19 UTC, ice-dionysos commented on coin-distribution/tracker.go
> +		workersMax = 100
It's a thread pool configuration.  I'm not sure what number will be right for our use case, so decided to use something generic.

2023-12-18 09:22 UTC, ice-dionysos commented on coin-distribution/tracker.go
> +group by
Just to remove the duplicates. Because the same transaction hash will be used for `N` records.

2023-12-18 09:31 UTC, ice-dionysos commented on coin-distribution/coin_distribution.go
> +	return errors.Wrap(cd.DB.Ping(ctx), "[health-check] failed to ping DB")
They do not have any health checks or pings.

2023-12-18 09:38 UTC, ice-ares commented on coin-distribution/contract.go
> +		CreatedAt  time.Time  `db:"created_at"`
Doesnt matter

2023-12-18 09:39 UTC, ice-ares commented on coin-distribution/contract.go
> +	batchMaxSizeLimit = 29_890_000
30 million users for 1 transaction?

2023-12-18 09:41 UTC, ice-ares commented on coin-distribution/processor.go
> +	records_count.num = $2 and
U have limit. Why would the count be different?

2023-12-18 09:49 UTC, ice-ares commented on coin-distribution/processor.go
> +				log.Warn(fmt.Sprintf("worker [%v]: signal channel is full", num))
Then Whats the point of that ticker? Just to tell us if load is too much?

2023-12-18 09:53 UTC, ice-ares commented on coin-distribution/tracker.go
> +		workersMax = 100
Then in needs to be scaled of something. For example on prod we have 8vCPU, scale it for that

2023-12-18 09:54 UTC, ice-ares commented on coin-distribution/tracker.go
> +group by
Then use distinct. Group by is heavy

2023-12-18 09:57 UTC, ice-dionysos commented on coin-distribution/contract.go
> +	batchMaxSizeLimit = 29_890_000
Yup. That's the physical limit.

2023-12-18 09:58 UTC, ice-dionysos commented on coin-distribution/processor.go
> +	records_count.num = $2 and
Because database can return N < LIMIT records. That check just ensures that we always have N == LIMIT.

2023-12-18 10:01 UTC, ice-dionysos commented on coin-distribution/contract.go
> +	batchMaxSizeLimit = 29_890_000
Nvm.

2023-12-18 10:16 UTC, ice-dionysos commented on coin-distribution/processor.go
> +				log.Warn(fmt.Sprintf("worker [%v]: signal channel is full", num))
For instance, coinDistributer may be blocked/disabled. Or just does not have enough data to process. That ticker will wake it up.

2023-12-18 13:04 UTC, ice-ares commented on coin-distribution/coin_distribution.go
> -		err := storage.DoInTransaction(reqCtx, cd.db, func(conn storage.QueryExecer) error {
btw, do u use this?

2023-12-18 19:19 UTC, ice-ares commented on coin-distribution/contract.go
> +		Ethereum struct {
add mapstructure tags for all of those to make sure they are found

2023-12-19 22:21 UTC, ice-ares commented on coin-distribution/client.go
> +		log.Error(err, "failed to call ethereum RPC (attempt "+strconv.Itoa(attempt)+")")
Those args are not template args. Those are fields. Fix all logs. Log.XX(justOneArgHere)

2023-12-19 22:21 UTC, ice-ares commented on coin-distribution/contract.go
> -		cancel context.CancelFunc
The purpose of that is for the children to kill the parent. So we dont have the parent acting healthy while children are unresponsive

2023-12-19 22:21 UTC, ice-ares commented on coin-distribution/contract.go
> +		BatchSize   int64 `yaml:"batchSize"   mapstructure:"batchSize"`   //nolint:tagalign // .
Do u need this?

2023-12-19 22:21 UTC, ice-ares commented on coin-distribution/processor.go
> +	return (proc.Conf.StartHours < proc.Conf.EndHours && (currentHour < proc.Conf.StartHours || currentHour > proc.Conf.EndHours)) ||
Can u check if this is correct? Its supposed to validate that u're inside a [start,end] where it can both work with [23,1] -2hours- and [1,23] -22hours-

2023-12-19 22:21 UTC, ice-ares commented on coin-distribution/coin_distribution.go
> +	cd.MustStart(ctx, nil, nil)
Why nil, nil?

2023-12-20 08:53 UTC, ice-dionysos commented on coin-distribution/coin_distribution.go
> +	cd.MustStart(ctx, nil, nil)
Those output channels are used for testing only right now.

2023-12-20 08:55 UTC, ice-dionysos commented on coin-distribution/contract.go
> -		cancel context.CancelFunc
Children will just call `Disable()` to stop any further processing.

2023-12-20 11:37 UTC, ice-ares commented on coin-distribution/coin_distribution.go
> -	go startPrepareCoinDistributionsForReviewMonitor(ctx, cd.db)
Bring this back

2023-12-20 15:05 UTC, ice-dionysos commented on coin-distribution/coin_distribution.go
> -	go startPrepareCoinDistributionsForReviewMonitor(ctx, cd.db)
What exactly ? `cancel` ?

2023-12-20 15:38 UTC, merged