Start staking implementation
ice-blockchain/freezer pull request #6
Opened 2022-05-17 22:18 UTC by azayats-leftclick

Start staking implementation
[Task](https://www.notion.so/leftclick/Implement-Start-Staking-3c6a3ad8db5c4d70a75c140f019d2805)

2022-05-18 07:53 UTC, nusanovkornilov-leftclick commented on economy/start_staking.go
> +	return res[0].IsValid(), nil
Not sure the way how invalid entities will appear in database, do we really need this validation? We have it on endpoint, and may be it is a good idea to add it to insertion method (in case of new ways to add them)

2022-05-18 08:15 UTC, victor-oancea-leftclick-io commented on economy/start_staking.go
> +	return res[0].IsValid(), nil
Yep, validations only in the endpoint controllers

2022-05-18 13:07 UTC, victor-oancea-leftclick-io requested changes

2022-05-18 13:07 UTC, victor-oancea-leftclick-io commented on cmd/freezer-refrigerant/contract.go
> +	stakingEnabled     = "STAKING_ENABLED"
STAKING_ALREADY_ENABLED

2022-05-18 13:07 UTC, victor-oancea-leftclick-io commented on economy/contract.go
> +	ErrStakingEnabled   = errors.New("staking enabled")
Staking already enabled

2022-05-18 13:07 UTC, victor-oancea-leftclick-io commented on economy/start_staking.go
> +	sql := fmt.Sprintf(`SELECT staking_years, staking_percentage
you just need to return a flag, just a bool column

2022-05-18 15:32 UTC, victor-oancea-leftclick-io commented on economy/start_staking.go
> +// SPDX-License-Identifier: BUSL-1.1
rename file to staking

2022-05-18 22:36 UTC, victor-oancea-leftclick-io approved these changes

2022-05-19 06:45 UTC, nusanovkornilov-leftclick approved these changes

2022-05-19 06:45 UTC, merged