implement new approach of caching for total coins stats endpoint
ice-blockchain/freezer pull request #79
Opened 2023-12-23 11:07 UTC by ice-cronus

Endpoint fetches data only from redis.
Each child interval we're updating value in redis for last parent interval
Build initial cache for 90 days on service startup

2023-12-23 13:28 UTC, ice-ares requested changes

2023-12-23 13:28 UTC, ice-ares commented on tokenomics/balance.go
> +	if responses, err := r.db.TxPipelined(ctx, func(pipeliner redis.Pipeliner) error {
Dont complicate things, just storage.Set is enough

2023-12-23 13:28 UTC, ice-ares commented on tokenomics/balance.go
> +			dwhCtx, cancel := context.WithTimeout(ctx, stdlibtime.Duration(0.20*float64(r.cfg.GlobalAggregationInterval.Child)))
Whats that strange value? Just set it to 1min

2023-12-23 13:28 UTC, ice-ares commented on tokenomics/balance.go
> +				return errors.Wrapf(r.buildTotalCoinCache(ctx, d), "failed to build/init total coins cache for %v", d)
Keep it simple. Infinite retry until it works

2023-12-23 13:28 UTC, ice-ares commented on tokenomics/balance.go
> +			dayMatch := stats.CreatedAt.Truncate(r.cfg.GlobalAggregationInterval.Parent).Equal(child.Date.Truncate(r.cfg.GlobalAggregationInterval.Parent))
U need to work with hours / child aggregate, not parent. Cuz a day is actually the xx:00 hour of the next.

2023-12-23 13:44 UTC, ice-cronus commented on tokenomics/balance.go
> +			dayMatch := stats.CreatedAt.Truncate(r.cfg.GlobalAggregationInterval.Parent).Equal(child.Date.Truncate(r.cfg.GlobalAggregationInterval.Parent))
So, we gonna store children in redis, not parents?

2023-12-23 13:55 UTC, ice-ares commented on tokenomics/balance.go
> +			dayMatch := stats.CreatedAt.Truncate(r.cfg.GlobalAggregationInterval.Parent).Equal(child.Date.Truncate(r.cfg.GlobalAggregationInterval.Parent))
Yep

2023-12-23 13:56 UTC, ice-ares commented on tokenomics/balance.go
> +			dayMatch := stats.CreatedAt.Truncate(r.cfg.GlobalAggregationInterval.Parent).Equal(child.Date.Truncate(r.cfg.GlobalAggregationInterval.Parent))
The dates that are calculated from days, are actually hours

2023-12-27 12:17 UTC, ice-ares commented on tokenomics/balance.go
> +func (r *repository) totalCoinsDates(now *time.Time, days uint64, dayInterval stdlibtime.Duration) ([]stdlibtime.Time, []*TotalCoinsTimeSeriesDataPoint) {
do u need that dayInterval stdlibtime.Duration?

2023-12-27 12:33 UTC, ice-cronus commented on tokenomics/balance.go
> +func (r *repository) totalCoinsDates(now *time.Time, days uint64, dayInterval stdlibtime.Duration) ([]stdlibtime.Time, []*TotalCoinsTimeSeriesDataPoint) {
Yes, that logic was initially used for building dates for fetching data on endpoint (with interval between times = one day / parent), but now we're using it for building initial cache (with interval = one hour / child) as well. We can change it to a bool flag and switch to child / parent inside instead.

2023-12-27 13:03 UTC, ice-ares commented on tokenomics/balance.go
> +			err = errors.Wrapf(r.buildTotalCoinCache(ctx, datesSameDay...), "failed to build/init total coins cache for %v", datesSameDay)
why do u call this twice?

2023-12-27 13:03 UTC, ice-ares commented on tokenomics/balance.go
> +		if !found {
why?

2023-12-27 13:08 UTC, ice-cronus commented on tokenomics/balance.go
> +			err = errors.Wrapf(r.buildTotalCoinCache(ctx, datesSameDay...), "failed to build/init total coins cache for %v", datesSameDay)
Infinite retry until it works. Is context approach with break better?
https://github.com/ice-blockchain/freezer/pull/79#discussion_r1435602231

2023-12-27 13:15 UTC, ice-ares commented on tokenomics/balance.go
> +			err = errors.Wrapf(r.buildTotalCoinCache(ctx, datesSameDay...), "failed to build/init total coins cache for %v", datesSameDay)
u have 2 calls to the same method, one after the other

2023-12-27 15:21 UTC, ice-cronus commented on tokenomics/balance.go
> +		if !found {
actually not needed, cuz we're fetching on endpoint only matched data, removed

2023-12-27 16:20 UTC, ice-ares requested changes

2023-12-27 16:20 UTC, ice-ares commented on tokenomics/balance_total_coins.go
> +				child.Total = child.Standard + child.PreStaking + child.Blockchain
remove + child.Blockchain

2023-12-27 16:20 UTC, ice-ares commented on tokenomics/balance_total_coins.go
> +			child.Date = child.Date.In(location).Add(-1 * stdlibtime.Nanosecond)
No, return it in utc

2023-12-27 16:20 UTC, ice-ares commented on tokenomics/balance_total_coins.go
> +	timeSinceMidnight := now.UTC().Sub(stdlibtime.Date(now.Year(), now.Month(), now.Day(), midnightHour, 0, 0, 0, stdlibtime.UTC))
What is this overengineeribg? Just Truncate to parent

2023-12-27 16:20 UTC, ice-ares commented on tokenomics/balance_total_coins.go
> +		date := now.Add(dayInterval * -1 * stdlibtime.Duration(day)).Add(-timeSinceMidnight).Truncate(truncationInterval)
If day == 0 
   Truncate to parent
Rlse 
Truncate to child

2023-12-27 16:20 UTC, ice-ares commented on tokenomics/balance_total_coins.go
> +	return errors.Wrapf(storage.Set(ctx, r.db, val...), "failed to set cache value for total coins: %+v", coins)
%#v

Just get a proper IDE that can highlight issues properly

2023-12-27 16:20 UTC, ice-ares commented on tokenomics/balance_total_coins.go
> +	workerPool := pond.New(routinesCountToInitCoinsCacheOnStartup, 0, pond.MinWorkers(routinesCountToInitCoinsCacheOnStartup))
10 goroutines in total, not min

2023-12-27 17:16 UTC, ice-cronus commented on tokenomics/balance_total_coins.go
> +	workerPool := pond.New(routinesCountToInitCoinsCacheOnStartup, 0, pond.MinWorkers(routinesCountToInitCoinsCacheOnStartup))
It is min and max (first arg), so 10 in total

2023-12-27 17:20 UTC, ice-cronus commented on tokenomics/balance_total_coins.go
> +		date := now.Add(dayInterval * -1 * stdlibtime.Duration(day)).Add(-timeSinceMidnight).Truncate(truncationInterval)
not needed, first element is added before (start). But we have to duplicate last entry with parent and child, like
```
2023-12-27T17:00:00 (-1ns = 27/12)
2023-12:27T00:00:00 (-1ns = 26/12) 
```

2023-12-28 10:26 UTC, ice-ares commented on tokenomics/balance_total_coins.go
> +				child.Total = child.Standard + child.PreStaking
Lets not do any math here. Keep em as is. Imma add the math to the dwh storage layer later on

2023-12-28 10:26 UTC, ice-ares commented on tokenomics/balance_total_coins.go
> +				err = errors.Wrapf(r.buildTotalCoinCache(ctx, date), "failed to build/init total coins cache for %v", fetchDate)
Ctx, fetchDate

2023-12-28 11:02 UTC, merged