Implement ICE Balance Update Batch Processing
ice-blockchain/freezer pull request #8
Opened 2022-06-02 13:03 UTC by antonh21

[Task](https://www.notion.so/leftclick/ee29b82f712f428bb3e469c9abdfebb5?v=a4babc49b4e54b2da2fdf08b8414849b&p=6df245f94fa64673a448175902aabb57)

TODO: write short descent description.

2022-06-06 09:00 UTC, victor-oancea-leftclick-io commented on economy/internal/storages/balances/balances.go
> +		"now":                uint64(time.Now().UnixNano()),
just time.Now()

2022-06-06 09:00 UTC, victor-oancea-leftclick-io commented on economy/internal/storages/balances/balances.go
> +	sql := getBalancesSQL()
Lets inline the sql

2022-06-06 09:01 UTC, victor-oancea-leftclick-io commented on economy/internal/storages/balances/balances.go
> +			return nil, errors.Wrapf(err, "db execute getting user economy for (chunk:%v, chunkIndex:%v) failed",
Thats not all the params in the sql

2022-06-06 09:03 UTC, victor-oancea-leftclick-io commented on economy/internal/storages/balances/balances.go
> +	for ctx.Err() == nil {
This is not how this should work.

Every message processing has only 1 batch of 1000 economies to process, in parallel

2022-06-06 09:04 UTC, victor-oancea-leftclick-io commented on economy/internal/storages/balances/balances.go
> +func getBalancesSQL() string {
I'll ignore this sql as well for now, I'll review it at the end

2022-06-06 09:13 UTC, antonh21 commented on economy/DDL.lua
> +                    active BOOLEAN NOT NULL DEFAULT false
Nope. For example we have 5 records. Boolean field is unique.
```
1 true
2 false
3 [can't be true or false because space has already these 2 values]
4 [can't be true or false because space has already these 2 values]
etc
```
Here can be unique only in 1 case: when we use `NULL` value instead of false.

2022-06-06 09:25 UTC, nusanovkornilov-leftclick requested changes

2022-06-06 09:25 UTC, nusanovkornilov-leftclick commented on economy/internal/storages/balances/balances.go
> +	if err = storage.CheckSQLDMLErr(query, err); err != nil {
You'll need to send any message to message broker with updated balance. We need to catch it in santa to update user's balance and achieve badges for ice amount (not sure what kind of balance is used in santa, it seems to be total, @victor-oancea-leftclick-io ?)

2022-06-06 09:27 UTC, victor-oancea-leftclick-io commented on economy/DDL.lua
> +                    active BOOLEAN NOT NULL DEFAULT false
Oh, right.

2022-06-06 09:29 UTC, victor-oancea-leftclick-io commented on economy/internal/storages/balances/balances.go
> +	if err = storage.CheckSQLDMLErr(query, err); err != nil {
The message will have all total variants

2022-06-06 09:34 UTC, antonh21 commented on economy/internal/storages/balances/balances.go
> +			return nil, errors.Wrapf(err, "db execute getting user economy for (chunk:%v, chunkIndex:%v) failed",
SQL or error description?

2022-06-06 09:41 UTC, antonh21 commented on economy/internal/storages/balances/balances.go
> +	for ctx.Err() == nil {
Could you please explain more detailed?
Now I send message with uuid and handle this message in this processor. How I implemented processor:
1. `SELECT ... `
2. `Handle all the records in parallel`:
```
wg := new(sync.WaitGroup)
	for _, u := range ue {
		wg.Add(1)
		go func(u *userEconomy) {
			handleGeneralBalances // total, standard, staking
			handleUsersBalances    // all others
			wg.Done()
		}(u)
	}
	wg.Wait()
```
I see that I should not to collect data by offsets and LIMIT 1000 is enough for the batch.

2022-06-06 21:07 UTC, antonh21 commented on economy/internal/storages/adoption/adoption.go
> +		SELECT GROUP_CONCAT(history.users_count) FROM (
This `GROUP_CONCAT` will select the same data for all records in the full request, right? Because we don't have any specific filtration for each record.
Is there any sense to get the same data (if I am right) for different records, then parse them if it can be done only once?
I mean:
```
field1    field2        field3
1              1        history
2              2        the same history
3              3        the same history
```
I think no.

So I think here SQL maybe can be written in another way, much easier to achieve the needed result.
You can try to focus not on adoption in the select, but on adoption history.

2022-06-06 21:22 UTC, antonh21 commented on economy/internal/storages/adoption/adoption_history.go
> +	sql := `SELECT count(1) AS c FROM user_economy WHERE last_mining_started_at > :timeBefore24Hours`
Here should be `last_mining_started_at > now - 24h` otherwise you don't have upper bounds for the results.

2022-06-06 21:28 UTC, antonh21 commented on economy/internal/storages/adoption/adoption.go
> +	UPDATE adoption SET active = CASE
I assume no need to use when-case here. Try this:
```
UPDATE adoption
SET active = adoption.total_active_users = :newAdoptionTotalUsers AND adoption.base_hourly_mining_rate = :newAdoptionRate
        WHERE 1 = 1
```

2022-06-07 07:48 UTC, nusanovkornilov-leftclick commented on economy/internal/storages/adoption/adoption.go
> +		SELECT GROUP_CONCAT(history.users_count) FROM (
They are the same for each record, right. I'll check if we can rewrite that SQL, because of it seems we need to check all latest 168 records from adoption_history for each adoption (as business logic said), it is done with golang for now, but may be we can move part of that logic to the SQL to reduce parsing

2022-06-27 12:07 UTC, merged